baseURL = "https://www.kouloumos.com/"
languageCode = 'en-us'
title = 'up to the bitcoin hill'
summaryLength = 2
theme = "cactus"
[permalinks]
  words = ":filename"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "words"
url = "/words"
weight = 2

[[menu.main]]
name = "logs"
url = "https://roamresearch.com/#/app/kouloumos/page/guSc-5608"
weight = 3
[menu.main.params]
  external = true


[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 1

           
[params]

  colortheme = "dark" # dark, light, white, or classic
  mainSection = "words"
  mainSectionTitle = "Words"
	logo = "images/path.png"
	description = "Low time preference dev pushing to work on the foundations of the new monetary system."
  showProjectsList = true
  projectsUrl = "https://github.com/kouloumos" # title link for projects list

  showUpcomingPost = true

	dateFormat = "January 2, 2006" # default
	# Post page settings
  show_updated = true # default
  showReadTime = true # default

[[params.social]]
  name = "github"
  link = "https://github.com/kouloumos"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/kouloumos"

[module]
# to import the css directly from the upstream dependency
[[module.mounts]]
  source = "./node_modules/@tremor/react/dist/esm/"
  target = "assets/css"
# When you add a mount, the default mount for the concerned target root is ignored
# so we need to explicitly add it. 
# see https://gohugo.io/hugo-modules/configuration/#module-config-mounts
[[module.mounts]]
  source = 'assets'
  target = 'assets'